### PR TITLE
implement entityframework in web application

### PR DESCRIPTION
**Pull request by dgequillo**
## General Description
Asana issue: https://app.asana.com/0/1111428436201563/1200634056055718/f

## Prerequisite / how to test
1. Click Customer menu to view customer details
2. Click Add Customer to add customer details
3. Click Edit to update customer details

### CODE REVIEW

**Comment by rjs123431** [comment]
@dgequillo some improvements needed:
- we should not bind our tables directly to the views. An example is for instance we want the customers page to include column for # of orders, it is hard to change or most likely has big effect to the code if you bind it directly. You should separate the db models (tables) from the view model. Like you can have CustomerViewModel and use this in the Views. If you want to forward this to the database you can just map it to Customer model and vice versa

- we should be able to configure the db models it will be use in migration. For instance we may want to name the table to **Customer** instead of **Customers**, or we can set length of Firstname to 64 characters only instead of Max. Use fluent api for this

**Comment by rjs123431** [comment]
@dgequillo if you need anything just let me know

**Comment by dgequillo** [comment]
@rjs123431 how to solve this issue sir? So sorry sir @rjs123431 
we should be able to configure the db models it will be use in migration. For instance we may want to name the table to Customer instead of Customers, or we can set length of Firstname to 64 characters only instead of Max. Use fluent api for this.

**Comment by rjs123431** [comment]
Search for "ef 6 fluent api" you can find a guide

**Comment by rjs123431** [comment]
And by the way, DO NOT change the `DefaultSchema`.

Configure only the table name and other property settings

**Comment by dgequillo** [comment]
I will Create another table sir or not necessary cause in the guide they use 2 table in database?

**Comment by rjs123431** [comment]
Not necessary, you only need Customer for this task

**Comment by rjs123431** [comment]
Just take your time, the important thing here is you understand what you are doing 👍

**Comment by dgequillo** [comment]
ok sir @rjs123431 
this is the code for my customercontext is it right sir rey?
 public class CustomerContext: DbContext
    {
        public CustomerContext() : base("CustomerContext")
        {
            
        }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<CustomersDTO> CustomersDTO { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            modelBuilder.Entity<Customers>().HasKey(c => c.Id);
            modelBuilder.Entity<Customers>().Property(c => c.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            modelBuilder.Entity<Customers>().Property(c => c.Firstname).HasMaxLength(64);
            modelBuilder.Entity<Customers>().Property(c => c.Middlename).HasMaxLength(64);
            modelBuilder.Entity<Customers>().Property(c => c.Lastname).HasMaxLength(64);
        }
    }

**Comment by dgequillo** [comment]
this is the code for controller sir.
is it right sir rey the mapping that i make?

public class CustomerController : Controller
    {
        CustomerContext db = new CustomerContext(); 
        // GET: Customer
        public ActionResult Index()
        { 
            ViewBag.Title = "Customer List";
            var list = db.Customers.ToList();
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Customers, CustomersDTO>());
            var mapper = new Mapper(config);
            var custDTO = mapper.Map<List<CustomersDTO>>(list);
            return View(custDTO);
        }
        [HttpGet]
        public ActionResult Create()
        {
            Customers model = new Customers();
            model.Birthday = DateTime.Today;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CustomersDTO data)
        {
            using (var db = new CustomerContext())
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<Customers, CustomersDTO>());
                var mapper = new Mapper(config);
                var cust = mapper.Map<Customers>(data);

                db.Customers.Add(cust);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Customers model = new Customers();
            model = db.Customers.FirstOrDefault(x => x.Id == id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Customers data)
        {
            using (var db = new CustomerContext())
            {
                var entity = db.Customers.FirstOrDefault(x => x.Id == data.Id);
                db.Entry(entity).CurrentValues.SetValues(data);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }

**Comment by rjs123431** [comment]
If you think it is working, please commit and push the changes, we can check it from there

**Comment by dgequillo** [comment]
ok sir @rjs123431 noted sir.

**Comment by dgequillo** [comment]
i have question sir rey if i will update the database i will use the package manager console sir rey?

**Comment by rjs123431** [comment]
> i have question sir rey if i will update the database i will use the package manager console sir rey?

yes, you may run `update-database` there, it will process all migrations

**Comment by dgequillo** [comment]
t
aea
  protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("dbo");
            modelBuilder.Entity<Customers>()
                .ToTable("Customer");

            modelBuilder.Entity<Customers>().HasKey(c => c.Id);
            modelBuilder.Entity<Customers>().Property(c => c.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            modelBuilder.Entity<Customers>().Property(c => c.Firstname).HasMaxLength(64);
            modelBuilder.Entity<Customers>().Property(c => c.Middlename).HasMaxLength(64);
            modelBuilder.Entity<Customers>().Property(c => c.Lastname).HasMaxLength(64);
            modelBuilder.Entity<Customers>().Property(c => c.Gender).HasMaxLength(10);
        }
this code sir rey is working when i update database in a package manager console the data type of the table and the name is changing Customers to Customer
But the problem is it will create also a table CustomersDTO in the database sir rey

**Comment by dgequillo** [comment]
@rjs123431 good pm sir rey i already push the code please check if the mapper that i make is right and also in changing the database table Name and data type is right.

**Comment by rjs123431** [comment]
Do you have skype or messenger I can call?

**Comment by rjs123431** [comment]
@dgequillo  please check if you can access this:

https://prod.liveshare.vsengsaas.visualstudio.com/join?A79E6CA11F6A79C2099A421C227591B967B8

**Comment by dgequillo** [comment]
yes sir i have messenger Daryl Gequillo

**Comment by dgequillo** [comment]
Thank You sir rey @rjs123431

**Review by jrvalenzona-bps — APPROVED** [review]
+2

**Pull request merged**
