### PR TITLE
Modify entityframework multiple relationships

### PR DESCRIPTION
**Pull request by dgequillo**
## GENERAL DESCRIPTION
Asana issue: https://app.asana.com/0/1111428436201563/1200682316015412/f

## Prerequisites /  How to test
1. Click products menu and click the add product button to add product.
2. Click edit button if you are going to edit the product.
3. Click orders menu it show the order details.
4. Click add order button to add orders.
5. Fill-up the information and click the button add product to add multiple product.
6. Click save button to save your orders.
7. Click edit button to edit orders.

### CODE REVIEW

**Comment by rjs123431** [comment]
@dgequillo good job on this.
I may have some comments but you don't need to change this PR.

1. In `Order Items` table, you might not need to include `ProductCode` and `ProductName` because it has a relationship the `Products` table. That is the main purpose of relationship and **table normalization**

2. Now that we have implemented relationships and navigation properties in our class, entity framework has a cool feature to load multiple related table in one query.

You can change this 2 database queries:
```
var order = db.Orders.FirstOrDefault(c => c.Id == id);
order.Items = db.OrdersItems.Where(x => x.OrderId == id).ToList();
```
to `var order = db.Orders.Include("Items").FirstOrDefault(c => c.Id == id);`
or `var order = db.Orders.Include("Items.Product").FirstOrDefault(c => c.Id == id);`

3. In the javascript side, we might prefer to use function at all time and don't use the jquery style binding.

This is jquery-style binding:
```
$("#bntaddProduct").click(function () {
});
```
the suggested way is to use function:
```
  function addProduct() {
          $.ajax({
              url: getProductsUrl,
              type: 'POST',
              success: function (result) {
                  $("#productModal").modal("show");
              }
          });
  }
```
and in the html, you can bind it the good old way
```
<button type="button" class="btn btn-success btn-md" id="bntaddProduct" onclick="addProduct()">
    Add Product
</button>
```
Notice the ` onclick="addProduct()"`

This way, your code is flexible because your function is independent from the button element, and you can call the `addProduct` function anyway you want.
A good use case will be `computeAmount`, you can call it on both quantity and price change (onblur)

4. For the UI and layouts, it is good to use `css` (`class="mt-30 mr-2"`) and not inline style (`style="margin-top: 30px; right:80%;"`)
See `Site.css` for reference

As I say, you do not need to change this PR. Just take note of those points I've mentioned and use it on your next actual project.  👍

**Comment by rjs123431** [comment]
@jrvalenzona-bps for reference. Thank you.

**Comment by dgequillo** [comment]
> @jrvalenzona-bps for reference. Thank you.

ok sir rey noted @rjs123431 thank you sir for the information.

**Review by rjs123431 — APPROVED** [review]
+2

**Pull request merged**
